version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
