name: auto-update

on:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  update-jpostcode-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Set up Ruby
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: update jpostcode data
      run: bundle exec rake jpostcode:data:update_all
      env:
        RUBYOPT: "-w" 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        base: master
        branch: update_jpostcode_data
        branch-suffix: timestamp
        delete-branch: true
        title: bundle exec rake jpostcode:data:update_all
        commit-message: bundle exec rake jpostcode:data:update_all
