name: auto-update

on:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  update-jpostcode-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: update jpostcode data
      run: bundle exec rake jpostcode:data:update_all
      env:
        RUBYOPT: "-w" 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        base: master
        branch: update_jpostcode_data
        branch-suffix: timestamp
        delete-branch: true
        title: bundle exec rake jpostcode:data:update_all
        commit-message: bundle exec rake jpostcode:data:update_all
